import '../models/training_model.dart';

class ExerciseLibraryService {
  static final List<ExerciseTemplate> _exercises = [
    // Chest Exercises
    ExerciseTemplate(
      id: '1',
      name: 'Push-ups',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Start in plank position, lower body until chest nearly touches floor, push back up.',
      tips: ['Keep core tight', 'Full range of motion', 'Control the movement'],
    ),
    ExerciseTemplate(
      id: '2',
      name: 'Bench Press',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up.',
      tips: ['Keep feet on ground', 'Squeeze shoulder blades', 'Control the descent'],
    ),
    ExerciseTemplate(
      id: '3',
      name: 'Dumbbell Flyes',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'dumbbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on bench, arms slightly bent, lower dumbbells in arc motion, squeeze chest.',
      tips: ['Slight bend in elbows', 'Feel the stretch', 'Squeeze at the top'],
    ),
    ExerciseTemplate(
      id: '14',
      name: 'Incline Bench Press',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on incline bench (30-45 degrees), lower bar to upper chest, press up.',
      tips: ['Focus on upper chest', 'Keep back against bench', 'Full range of motion'],
    ),
    ExerciseTemplate(
      id: '15',
      name: 'Decline Bench Press',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on decline bench, lower bar to lower chest, press up.',
      tips: ['Targets lower chest', 'Secure feet', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '16',
      name: 'Cable Flyes',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'cable',
      difficultyLevel: 'intermediate',
      instructions: 'Stand between cable machines, arms extended, bring handles together in arc motion.',
      tips: ['Slight bend in elbows', 'Constant tension', 'Squeeze chest at center'],
    ),
    ExerciseTemplate(
      id: '17',
      name: 'Chest Dips',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'dip_bar',
      difficultyLevel: 'intermediate',
      instructions: 'Grip parallel bars, lean forward, lower body, push back up.',
      tips: ['Lean forward for chest focus', 'Full range of motion', 'Control descent'],
    ),
    ExerciseTemplate(
      id: '18',
      name: 'Incline Dumbbell Press',
      category: 'strength',
      targetMuscle: 'chest',
      equipment: 'dumbbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on incline bench, press dumbbells up and together.',
      tips: ['Upper chest focus', 'Keep back flat', 'Control the weight'],
    ),

    // Leg Exercises
    ExerciseTemplate(
      id: '4',
      name: 'Squats',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Stand with feet shoulder-width apart, sit back and down, keep chest up.',
      tips: ['Keep knees behind toes', 'Weight in heels', 'Full depth if possible'],
    ),
    ExerciseTemplate(
      id: '5',
      name: 'Lunges',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Step forward, lower hips until both knees at 90 degrees, push back up.',
      tips: ['Keep torso upright', 'Step far enough forward', 'Control the movement'],
    ),
    ExerciseTemplate(
      id: '6',
      name: 'Deadlifts',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'barbell',
      difficultyLevel: 'advanced',
      instructions: 'Stand with bar over mid-foot, bend at hips and knees, grip bar, stand up straight.',
      tips: ['Keep back straight', 'Bar close to body', 'Drive through heels'],
    ),
    ExerciseTemplate(
      id: '19',
      name: 'Leg Press',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'machine',
      difficultyLevel: 'beginner',
      instructions: 'Sit in machine, feet on platform, push platform away, lower with control.',
      tips: ['Don\'t lock knees', 'Full range of motion', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '20',
      name: 'Leg Curls',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'machine',
      difficultyLevel: 'beginner',
      instructions: 'Lie face down, curl legs up toward glutes, lower with control.',
      tips: ['Focus on hamstrings', 'Squeeze at top', 'Slow negative'],
    ),
    ExerciseTemplate(
      id: '21',
      name: 'Leg Extensions',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'machine',
      difficultyLevel: 'beginner',
      instructions: 'Sit in machine, extend legs straight, lower with control.',
      tips: ['Focus on quads', 'Full extension', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '22',
      name: 'Romanian Deadlifts',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Hold bar, hinge at hips, lower bar down legs, feel hamstring stretch.',
      tips: ['Keep back straight', 'Feel the stretch', 'Slight knee bend'],
    ),
    ExerciseTemplate(
      id: '23',
      name: 'Bulgarian Split Squats',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'dumbbell',
      difficultyLevel: 'intermediate',
      instructions: 'Rear foot elevated on bench, lunge down on front leg, push back up.',
      tips: ['Keep torso upright', 'Front knee tracks over toe', 'Balance and control'],
    ),
    ExerciseTemplate(
      id: '24',
      name: 'Calf Raises',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Stand on edge of step, raise up on toes, lower heels below step level.',
      tips: ['Full range of motion', 'Pause at top', 'Control the descent'],
    ),
    ExerciseTemplate(
      id: '25',
      name: 'Front Squats',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'barbell',
      difficultyLevel: 'advanced',
      instructions: 'Bar on front shoulders, elbows high, squat down keeping torso upright.',
      tips: ['Keep elbows high', 'Stay upright', 'Quad focused'],
    ),
    ExerciseTemplate(
      id: '26',
      name: 'Goblet Squats',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbell at chest, squat down between legs, drive back up.',
      tips: ['Keep chest up', 'Elbows inside knees', 'Good for learning squat form'],
    ),
    ExerciseTemplate(
      id: '27',
      name: 'Step-ups',
      category: 'strength',
      targetMuscle: 'legs',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Step up onto box or bench with one leg, drive through heel, step down.',
      tips: ['Drive through heel', 'Full extension at top', 'Control descent'],
    ),

    // Back Exercises
    ExerciseTemplate(
      id: '7',
      name: 'Pull-ups',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'pullup_bar',
      difficultyLevel: 'intermediate',
      instructions: 'Hang from bar, pull body up until chin over bar, lower with control.',
      tips: ['Full range of motion', 'Don\'t swing', 'Squeeze shoulder blades'],
    ),
    ExerciseTemplate(
      id: '8',
      name: 'Bent-over Rows',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Bend forward at hips, pull bar to lower chest, squeeze shoulder blades.',
      tips: ['Keep back straight', 'Pull to sternum', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '28',
      name: 'Lat Pulldown',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'cable',
      difficultyLevel: 'beginner',
      instructions: 'Sit at machine, pull bar down to upper chest, squeeze shoulder blades.',
      tips: ['Don\'t lean back too much', 'Pull to chest', 'Control the return'],
    ),
    ExerciseTemplate(
      id: '29',
      name: 'Seated Cable Row',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'cable',
      difficultyLevel: 'beginner',
      instructions: 'Sit at cable machine, pull handles to torso, squeeze shoulder blades.',
      tips: ['Keep back straight', 'Pull to lower chest', 'Squeeze at the back'],
    ),
    ExerciseTemplate(
      id: '30',
      name: 'T-Bar Row',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Straddle bar, bent over, pull bar to chest with both hands.',
      tips: ['Keep back flat', 'Pull to sternum', 'Squeeze shoulder blades'],
    ),
    ExerciseTemplate(
      id: '31',
      name: 'Single-Arm Dumbbell Row',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'One knee on bench, row dumbbell to hip, squeeze back.',
      tips: ['Keep back flat', 'Pull to hip', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '32',
      name: 'Face Pulls',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'cable',
      difficultyLevel: 'beginner',
      instructions: 'Pull rope attachment to face, separate handles at face level.',
      tips: ['Focus on rear delts', 'Pull to face', 'Squeeze shoulder blades'],
    ),
    ExerciseTemplate(
      id: '33',
      name: 'Chin-ups',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'pullup_bar',
      difficultyLevel: 'intermediate',
      instructions: 'Hang from bar with underhand grip, pull up until chin over bar.',
      tips: ['Underhand grip', 'Full range', 'More bicep involvement'],
    ),
    ExerciseTemplate(
      id: '34',
      name: 'Inverted Rows',
      category: 'strength',
      targetMuscle: 'back',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Hang under bar, pull chest to bar, lower with control.',
      tips: ['Keep body straight', 'Pull to chest', 'Good for beginners'],
    ),

    // Shoulder Exercises
    ExerciseTemplate(
      id: '35',
      name: 'Overhead Press',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Bar at shoulders, press overhead, lower with control.',
      tips: ['Keep core tight', 'Press straight up', 'Full range of motion'],
    ),
    ExerciseTemplate(
      id: '36',
      name: 'Lateral Raises',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbells at sides, raise arms out to sides to shoulder height.',
      tips: ['Slight bend in elbows', 'Lead with elbows', 'Control the descent'],
    ),
    ExerciseTemplate(
      id: '37',
      name: 'Front Raises',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbells at thighs, raise arms forward to shoulder height.',
      tips: ['Slight bend in elbows', 'Don\'t swing', 'Control the movement'],
    ),
    ExerciseTemplate(
      id: '38',
      name: 'Rear Delt Flyes',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Bent over, arms hanging, raise dumbbells out to sides.',
      tips: ['Focus on rear delts', 'Slight bend in elbows', 'Squeeze shoulder blades'],
    ),
    ExerciseTemplate(
      id: '39',
      name: 'Arnold Press',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'dumbbell',
      difficultyLevel: 'intermediate',
      instructions: 'Start with palms facing you, rotate and press overhead.',
      tips: ['Smooth rotation', 'Full range', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '40',
      name: 'Upright Rows',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Hold bar at thighs, pull up to chin, elbows high.',
      tips: ['Elbows lead', 'Pull to chin', 'Control the descent'],
    ),
    ExerciseTemplate(
      id: '41',
      name: 'Shrugs',
      category: 'strength',
      targetMuscle: 'shoulders',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbells at sides, shrug shoulders up, squeeze traps.',
      tips: ['Straight up and down', 'Squeeze at top', 'No rolling'],
    ),

    // Arms - Biceps
    ExerciseTemplate(
      id: '42',
      name: 'Barbell Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'barbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold bar at thighs, curl up to shoulders, squeeze biceps.',
      tips: ['Keep elbows at sides', 'Don\'t swing', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '43',
      name: 'Dumbbell Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbells at sides, curl up alternating or together.',
      tips: ['Keep elbows still', 'Full range of motion', 'Squeeze at top'],
    ),
    ExerciseTemplate(
      id: '44',
      name: 'Hammer Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbells with neutral grip, curl up keeping palms facing.',
      tips: ['Neutral grip throughout', 'Targets brachialis', 'Control the movement'],
    ),
    ExerciseTemplate(
      id: '45',
      name: 'Preacher Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Arms on preacher bench, curl weight up, squeeze biceps.',
      tips: ['Full stretch at bottom', 'Isolates biceps', 'Don\'t swing'],
    ),
    ExerciseTemplate(
      id: '46',
      name: 'Concentration Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Seated, elbow on inner thigh, curl weight up.',
      tips: ['Focus on bicep peak', 'Squeeze at top', 'Control descent'],
    ),
    ExerciseTemplate(
      id: '47',
      name: 'Cable Curls',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'cable',
      difficultyLevel: 'beginner',
      instructions: 'Stand at cable machine, curl handle up, squeeze biceps.',
      tips: ['Constant tension', 'Keep elbows still', 'Control the weight'],
    ),

    // Arms - Triceps
    ExerciseTemplate(
      id: '48',
      name: 'Tricep Dips',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dip_bar',
      difficultyLevel: 'intermediate',
      instructions: 'Grip bars, body upright, lower and press back up.',
      tips: ['Keep body upright', 'Full range', 'Lock out at top'],
    ),
    ExerciseTemplate(
      id: '49',
      name: 'Tricep Pushdowns',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'cable',
      difficultyLevel: 'beginner',
      instructions: 'Stand at cable, push handle down, extend arms fully.',
      tips: ['Keep elbows at sides', 'Full extension', 'Squeeze triceps'],
    ),
    ExerciseTemplate(
      id: '50',
      name: 'Overhead Tricep Extension',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Hold dumbbell overhead, lower behind head, extend back up.',
      tips: ['Keep elbows in', 'Full stretch', 'Control the weight'],
    ),
    ExerciseTemplate(
      id: '51',
      name: 'Close-Grip Bench Press',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Bench press with hands closer together, focus on triceps.',
      tips: ['Hands shoulder-width', 'Tuck elbows', 'Lower to lower chest'],
    ),
    ExerciseTemplate(
      id: '52',
      name: 'Skull Crushers',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'barbell',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on bench, lower bar to forehead, extend back up.',
      tips: ['Keep elbows in', 'Control the descent', 'Full extension'],
    ),
    ExerciseTemplate(
      id: '53',
      name: 'Tricep Kickbacks',
      category: 'strength',
      targetMuscle: 'arms',
      equipment: 'dumbbell',
      difficultyLevel: 'beginner',
      instructions: 'Bent over, elbow at 90 degrees, extend arm back.',
      tips: ['Keep upper arm still', 'Full extension', 'Squeeze triceps'],
    ),

    // Core Exercises
    ExerciseTemplate(
      id: '9',
      name: 'Plank',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Hold push-up position, keep body straight from head to heels.',
      tips: ['Don\'t let hips sag', 'Breathe normally', 'Engage core'],
    ),
    ExerciseTemplate(
      id: '10',
      name: 'Crunches',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Lie on back, knees bent, lift shoulder blades off ground.',
      tips: ['Don\'t pull on neck', 'Focus on abs', 'Controlled movement'],
    ),
    ExerciseTemplate(
      id: '54',
      name: 'Russian Twists',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'intermediate',
      instructions: 'Seated, lean back, rotate torso side to side.',
      tips: ['Keep core engaged', 'Control the rotation', 'Can add weight'],
    ),
    ExerciseTemplate(
      id: '55',
      name: 'Bicycle Crunches',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Lie on back, bring opposite elbow to knee in cycling motion.',
      tips: ['Full rotation', 'Touch elbow to knee', 'Controlled pace'],
    ),
    ExerciseTemplate(
      id: '56',
      name: 'Leg Raises',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'intermediate',
      instructions: 'Lie on back, raise legs up to 90 degrees, lower with control.',
      tips: ['Keep lower back down', 'Don\'t swing', 'Focus on lower abs'],
    ),
    ExerciseTemplate(
      id: '57',
      name: 'Hanging Leg Raises',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'pullup_bar',
      difficultyLevel: 'advanced',
      instructions: 'Hang from bar, raise legs up to 90 degrees or higher.',
      tips: ['Don\'t swing', 'Raise knees or straight legs', 'Control descent'],
    ),
    ExerciseTemplate(
      id: '58',
      name: 'Side Plank',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Lie on side, prop up on elbow, hold body straight.',
      tips: ['Keep hips up', 'Don\'t sag', 'Targets obliques'],
    ),
    ExerciseTemplate(
      id: '59',
      name: 'Ab Wheel Rollout',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'ab_wheel',
      difficultyLevel: 'advanced',
      instructions: 'Kneel, roll wheel forward, return to start.',
      tips: ['Keep core tight', 'Don\'t let back sag', 'Start on knees'],
    ),
    ExerciseTemplate(
      id: '60',
      name: 'Dead Bug',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Lie on back, extend opposite arm and leg, alternate sides.',
      tips: ['Keep lower back down', 'Slow and controlled', 'Full extension'],
    ),
    ExerciseTemplate(
      id: '61',
      name: 'Bird Dog',
      category: 'strength',
      targetMuscle: 'core',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'On hands and knees, extend opposite arm and leg, alternate.',
      tips: ['Keep back flat', 'Balance and control', 'Don\'t rotate hips'],
    ),

    // Cardio Exercises
    ExerciseTemplate(
      id: '11',
      name: 'Jumping Jacks',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Jump feet apart while raising arms overhead, jump back to starting position.',
      tips: ['Land softly', 'Keep rhythm', 'Stay light on feet'],
    ),
    ExerciseTemplate(
      id: '12',
      name: 'Burpees',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'advanced',
      instructions: 'Squat down, jump back to plank, do push-up, jump feet forward, jump up.',
      tips: ['Maintain form when tired', 'Breathe consistently', 'Modify if needed'],
    ),
    ExerciseTemplate(
      id: '13',
      name: 'Mountain Climbers',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'intermediate',
      instructions: 'Start in plank, alternate bringing knees to chest rapidly.',
      tips: ['Keep hips level', 'Fast but controlled', 'Engage core'],
    ),
    ExerciseTemplate(
      id: '62',
      name: 'Running',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Outdoor or treadmill running at various paces and distances.',
      tips: ['Proper running form', 'Breathe rhythmically', 'Warm up first'],
    ),
    ExerciseTemplate(
      id: '63',
      name: 'Cycling',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'machine',
      difficultyLevel: 'beginner',
      instructions: 'Stationary or outdoor cycling at various intensities.',
      tips: ['Adjust seat height', 'Maintain cadence', 'Good for low impact'],
    ),
    ExerciseTemplate(
      id: '64',
      name: 'Rowing',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'machine',
      difficultyLevel: 'intermediate',
      instructions: 'Use rowing machine with proper form: legs, core, arms.',
      tips: ['Drive with legs first', 'Full body movement', 'Control the recovery'],
    ),
    ExerciseTemplate(
      id: '65',
      name: 'Jump Rope',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'jump_rope',
      difficultyLevel: 'beginner',
      instructions: 'Jump over rope with both feet or alternating, maintain rhythm.',
      tips: ['Stay on balls of feet', 'Use wrists to turn rope', 'Great for conditioning'],
    ),
    ExerciseTemplate(
      id: '66',
      name: 'Box Jumps',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'box',
      difficultyLevel: 'intermediate',
      instructions: 'Jump onto box or platform, step down, repeat.',
      tips: ['Land softly', 'Full hip extension at top', 'Start with lower box'],
    ),
    ExerciseTemplate(
      id: '67',
      name: 'High Knees',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Run in place bringing knees up to waist level rapidly.',
      tips: ['Drive knees high', 'Quick foot turnover', 'Pump arms'],
    ),
    ExerciseTemplate(
      id: '68',
      name: 'Butt Kicks',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Run in place kicking heels up toward glutes.',
      tips: ['Quick turnover', 'Stay on balls of feet', 'Good for hamstrings'],
    ),
    ExerciseTemplate(
      id: '69',
      name: 'Sprints',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'advanced',
      instructions: 'Short distance all-out running efforts with rest periods.',
      tips: ['Full warm-up essential', 'Explosive effort', 'Complete recovery between'],
    ),
    ExerciseTemplate(
      id: '70',
      name: 'Stair Climbing',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'bodyweight',
      difficultyLevel: 'beginner',
      instructions: 'Climb stairs at steady or varied pace.',
      tips: ['Use full foot', 'Maintain upright posture', 'Great for legs'],
    ),

    // Full Body / Compound Exercises
    ExerciseTemplate(
      id: '71',
      name: 'Kettlebell Swings',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'kettlebell',
      difficultyLevel: 'intermediate',
      instructions: 'Hinge at hips, swing kettlebell between legs and up to shoulder height.',
      tips: ['Drive with hips', 'Keep back straight', 'Explosive movement'],
    ),
    ExerciseTemplate(
      id: '72',
      name: 'Clean and Press',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'barbell',
      difficultyLevel: 'advanced',
      instructions: 'Clean bar to shoulders, press overhead in one fluid movement.',
      tips: ['Explosive pull', 'Catch at shoulders', 'Full overhead lockout'],
    ),
    ExerciseTemplate(
      id: '73',
      name: 'Thrusters',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'barbell',
      difficultyLevel: 'advanced',
      instructions: 'Front squat, then press overhead without pausing.',
      tips: ['Fluid movement', 'Use momentum from squat', 'Full lockout'],
    ),
    ExerciseTemplate(
      id: '74',
      name: 'Wall Balls',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'medicine_ball',
      difficultyLevel: 'intermediate',
      instructions: 'Squat with ball, stand and throw ball to target on wall.',
      tips: ['Catch and immediately squat', 'Full depth squat', 'Aim for consistent target'],
    ),
    ExerciseTemplate(
      id: '75',
      name: 'Turkish Get-ups',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'kettlebell',
      difficultyLevel: 'advanced',
      instructions: 'From lying, stand up holding kettlebell overhead, reverse back down.',
      tips: ['Keep eyes on weight', 'Slow and controlled', 'Great for stability'],
    ),
    ExerciseTemplate(
      id: '76',
      name: 'Battle Ropes',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'battle_rope',
      difficultyLevel: 'intermediate',
      instructions: 'Create waves with heavy ropes using various arm patterns.',
      tips: ['Maintain core stability', 'Quick arm movement', 'Intense cardio'],
    ),
    ExerciseTemplate(
      id: '77',
      name: 'Farmer\'s Walk',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'dumbbell',
      difficultyLevel: 'intermediate',
      instructions: 'Hold heavy weights at sides, walk for distance or time.',
      tips: ['Keep shoulders back', 'Tight core', 'Great for grip strength'],
    ),
    ExerciseTemplate(
      id: '78',
      name: 'Sled Push',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'sled',
      difficultyLevel: 'intermediate',
      instructions: 'Push weighted sled across floor or turf.',
      tips: ['Low body position', 'Drive with legs', 'Full body power'],
    ),
    ExerciseTemplate(
      id: '79',
      name: 'Sled Pull',
      category: 'strength',
      targetMuscle: 'full_body',
      equipment: 'sled',
      difficultyLevel: 'intermediate',
      instructions: 'Pull weighted sled toward you using rope or handles.',
      tips: ['Engage posterior chain', 'Controlled pull', 'Full body tension'],
    ),
    ExerciseTemplate(
      id: '80',
      name: 'Medicine Ball Slams',
      category: 'cardio',
      targetMuscle: 'full_body',
      equipment: 'medicine_ball',
      difficultyLevel: 'beginner',
      instructions: 'Raise ball overhead, slam down forcefully, catch and repeat.',
      tips: ['Use full body', 'Explosive movement', 'Great for power'],
    ),
  ];

  List<ExerciseTemplate> getAllExercises() {
    return List.from(_exercises);
  }

  List<ExerciseTemplate> getExercisesByCategory(String category) {
    return _exercises.where((exercise) => exercise.category == category).toList();
  }

  List<ExerciseTemplate> getExercisesByMuscle(String muscle) {
    return _exercises.where((exercise) => exercise.targetMuscle == muscle).toList();
  }

  List<ExerciseTemplate> getExercisesByEquipment(String equipment) {
    return _exercises.where((exercise) => exercise.equipment == equipment).toList();
  }

  List<ExerciseTemplate> getExercisesByDifficulty(String difficulty) {
    return _exercises.where((exercise) => exercise.difficultyLevel == difficulty).toList();
  }

  ExerciseTemplate? getExerciseById(String id) {
    try {
      return _exercises.firstWhere((exercise) => exercise.id == id);
    } catch (e) {
      return null;
    }
  }

  List<String> getAvailableCategories() {
    return _exercises.map((e) => e.category).toSet().toList();
  }

  List<String> getAvailableMuscles() {
    return _exercises.map((e) => e.targetMuscle).toSet().toList();
  }

  List<String> getAvailableEquipment() {
    return _exercises.map((e) => e.equipment).toSet().toList();
  }

  List<ExerciseTemplate> searchExercises(String query) {
    final lowerQuery = query.toLowerCase();
    return _exercises.where((exercise) =>
        exercise.name.toLowerCase().contains(lowerQuery) ||
        exercise.targetMuscle.toLowerCase().contains(lowerQuery) ||
        exercise.category.toLowerCase().contains(lowerQuery)
    ).toList();
  }

  void addCustomExercise(ExerciseTemplate exercise) {
    _exercises.add(exercise);
  }

  List<ExerciseTemplate> getCustomExercisesByTrainer(String trainerId) {
    return _exercises.where((exercise) =>
        exercise.isCustom && exercise.createdBy == trainerId).toList();
  }

  List<ExerciseTemplate> getAllCustomExercises() {
    return _exercises.where((exercise) => exercise.isCustom).toList();
  }

  bool deleteCustomExercise(String exerciseId, String trainerId) {
    final index = _exercises.indexWhere((exercise) =>
        exercise.id == exerciseId &&
        exercise.isCustom &&
        exercise.createdBy == trainerId);

    if (index != -1) {
      _exercises.removeAt(index);
      return true;
    }
    return false;
  }
}