/// @file localization_service.dart
/// @brief Service for managing app translations
/// @details Provides translations for English and Romanian languages

class LocalizationService {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'app_name': 'Fitness Training Platform',
      'loading': 'Loading...',
      'save': 'Save',
      'save_changes': 'Save Changes',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'create': 'Create',
      'update': 'Update',
      'confirm': 'Confirm',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'search': 'Search',
      'filter': 'Filter',
      'clear': 'Clear',
      'select': 'Select',
      'none': 'None',
      'all': 'All',
      'refresh': 'Refresh',
      'logout': 'Logout',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'templates': 'Templates',
      'library': 'Library',
      'new_workout': 'New Workout',
      'view': 'View',
      'details': 'Details',
      'assigned': 'Assigned',
      'completed': 'Completed',
      'pending': 'Pending',
      'no_data_available': 'No data available',
      'assigned_to': 'Assigned to',
      'created_by': 'Created by',
      'created_at': 'Created at',
      'due_date': 'Due Date',
      'start_date': 'Start Date',
      'end_date': 'End Date',

      // Auth
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'confirm_password': 'Confirm Password',
      'login_button': 'Login',
      'register_button': 'Register',
      'have_account': 'Already have an account?',
      'no_account': 'Don\'t have an account?',
      'login_link': 'Login here',
      'register_link': 'Register here',
      'welcome_back': 'Welcome Back',
      'create_account': 'Create Account',

      // Dashboard
      'dashboard': 'Dashboard',
      'admin_dashboard': 'Admin Dashboard',
      'trainer_dashboard': 'Trainer Dashboard',
      'trainee_dashboard': 'Trainee Dashboard',

      // Tabs
      'trainees': 'Trainees',
      'workouts': 'Workouts',
      'assigned_workouts': 'Assigned Workouts',
      'goals': 'Goals',
      'assigned_goals': 'Assigned Goals',
      'nutrition': 'Nutrition',
      'assigned_nutrition': 'Assigned Nutrition Plan',
      'progress': 'Progress',

      // Users
      'users': 'Users',
      'add_user': 'Add User',
      'edit_user': 'Edit User',
      'user_type': 'User Type',
      'trainer': 'Trainer',
      'trainee': 'Trainee',
      'admin': 'Admin',
      'assign_trainer': 'Assign Trainer',
      'select_trainer': 'Select Trainer',
      'no_trainer': 'No Trainer',

      // Workouts
      'create_workout': 'Create Workout',
      'workout_name': 'Workout Name',
      'workout_date': 'Workout Date',
      'exercises': 'Exercises',
      'add_exercise': 'Add Exercise',
      'exercise_name': 'Exercise Name',
      'sets': 'Sets',
      'reps': 'Reps',
      'weight': 'Weight',
      'duration': 'Duration',
      'distance': 'Distance',
      'rest_time': 'Rest Time',
      'difficulty': 'Difficulty',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'category': 'Category',
      'strength': 'Strength',
      'cardio': 'Cardio',
      'flexibility': 'Flexibility',
      'equipment': 'Equipment',
      'bodyweight': 'Bodyweight',
      'barbell': 'Barbell',
      'dumbbell': 'Dumbbell',
      'machine': 'Machine',
      'cable': 'Cable',

      // Nutrition
      'nutrition_plan': 'Nutrition Plan',
      'assign_nutrition': 'Assign Nutrition',
      'daily_calories': 'Daily Calories',
      'daily_caloric_target': 'Daily Caloric Target',
      'daily_caloric_limit': 'Daily Caloric Limit',
      'recipe_ideas': 'Recipe Ideas',
      'recipes': 'Recipes',
      'ingredients': 'Ingredients',
      'instructions': 'Instructions',
      'calories': 'Calories',
      'log_food': 'Log Food Intake',
      'food_name': 'Food Name',
      'food_log': 'Food Log',
      'view_food_log': 'View Food Log',
      'consumed': 'Consumed',
      'target': 'Target',
      'remaining': 'Remaining',
      'exceeded': 'Exceeded',
      'todays_food_log': 'Today\'s Food Log',
      'logged_food_items': 'Logged Food Items',
      'no_food_logged': 'No food logged for this date',
      'add_item': 'Add Item',

      // Goals
      'create_goal': 'Create Goal',
      'goal_name': 'Goal Name',
      'goal_type': 'Goal Type',
      'target_value': 'Target Value',
      'current_value': 'Current Value',
      'deadline': 'Deadline',
      'status': 'Status',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'completed': 'Completed',

      // Progress
      'view_progress': 'View Progress',
      'body_measurements': 'Body Measurements',
      'weight': 'Weight',
      'height': 'Height',
      'body_fat': 'Body Fat',
      'muscle_mass': 'Muscle Mass',
      'date': 'Date',

      // Messages
      'no_data': 'No data available',
      'no_trainees': 'No trainees available',
      'no_workouts': 'No workouts assigned',
      'no_goals': 'No goals assigned',
      'no_nutrition_plan': 'No nutrition plan assigned',
      'error_loading_data': 'Error loading data',
      'success_create': 'Created successfully',
      'success_update': 'Updated successfully',
      'success_delete': 'Deleted successfully',
      'confirm_delete': 'Are you sure you want to delete?',

      // Tooltips
      'tooltip_create_workout': 'Create Workout',
      'tooltip_assign_nutrition': 'Assign Nutrition',
      'tooltip_create_goal': 'Create Goal',
      'tooltip_view_progress': 'View Progress',
      'tooltip_view_food_log': 'View Food Log',

      // Buttons
      'new_workout': 'New Workout',
      'add_trainee': 'Add Trainee',
      'template': 'Template',
      'schedule': 'Schedule',
      'test': 'Test',
      'create_goal': 'Create Goal',
      'view_food_log': 'View Food Log',
      'duplicate': 'Duplicate',
      'view_details': 'View Details',
      'progress_report': 'Progress Report',

      // Messages
      'found_trainees': 'Found {count} trainees assigned to you',
      'no_trainees_yet': 'No trainees yet',
      'trainees_appear_here': 'Trainees will appear here when assigned to you',
      'workouts_assigned_completed': 'Workouts: {assigned} assigned, {completed} completed',
      'create_workout': 'Create Workout',
      'assign_nutrition': 'Assign Nutrition',
      'created_workouts_total': 'Created {count} workouts total',
      'no_workouts_created_yet': 'No workouts created yet',
      'create_first_workout': 'Create your first workout using the + button or Test button',
      'exercises_duration': '{exercises} exercises • {duration} min',
      'scheduled': 'Scheduled',
      'created_goals_total': 'Created {count} goals total',
      'no_goals_created_yet': 'No goals created yet',
      'create_first_goal': 'Create your first goal using the Create Goal button',
      'progress': 'Progress',
      'deadline_days_remaining': 'Deadline: {days} days remaining',
      'deadline_overdue': 'Deadline: Overdue',
      'assigned_nutrition_plans_count': 'Assigned Nutrition Plans ({count})',
      'no_nutrition_plans_assigned': 'No Nutrition Plans Assigned',
      'assign_plans_from_trainees_tab': 'Assign nutrition plans to trainees from the Trainees tab',
      'unknown_trainee': 'Unknown Trainee',
      'kcal_per_day': '{calories} kcal/day',
      'recipes_count': '{count} recipes',
      'created': 'Created',

      // Dialogs
      'logout': 'Logout',
      'are_you_sure_logout': 'Are you sure you want to logout?',
      'confirm_delete': 'Are you sure you want to delete?',
      'delete_goal': 'Delete Goal',
      'delete_workout': 'Delete Workout',
      'notifications': 'Notifications',
      'create_new_workout': 'Create New Workout',
      'select_trainee': 'Select Trainee',
      'select_trainee_to_create_workout': 'Select a trainee to create a workout for:',
      'use_template': 'Use Template',
      'select_trainee_to_create_this_workout': 'Select a trainee to create this workout for:',
      'trainee_progress': '{name} Progress',
      'progress_charts_shown': 'Progress charts and statistics would be shown here.',
      'workout_completion_rate': 'Workout completion rate',
      'strength_progression': 'Strength progression',
      'weight_changes': 'Weight changes',
      'goal_achievements': 'Goal achievements',
      'workout_statistics': 'Workout Statistics',
      'assigned_workouts': 'Assigned workouts',
      'member_since': 'Member since',

      // Trainee Dashboard
      'my_user_id': 'My User ID',
      'my_name': 'My Name',
      'my_email': 'My Email',
      'workouts_found': 'Workouts found',
      'refresh_debug': 'Refresh & Debug',
      'no_workouts_assigned_yet': 'No workouts assigned yet',
      'trainer_will_assign_soon': 'Your trainer will assign workouts soon',
      'use_refresh_button': 'Use the Refresh button above to check for new workouts',
      'edit_results': 'Edit Results',
      'start_workout': 'Start Workout',
      'continue_workout': 'Continue Workout',
      'notes': 'Notes',
      'log_food_intake': 'Log Food Intake',
      'update_todays_steps': 'Update Today\'s Steps',
      'log_steps_manually': 'Log Steps Manually',
      'enter_step_count': 'Enter step count',
      'please_enter_step_count': 'Please enter step count',
      'please_enter_valid_number': 'Please enter a valid number',
      'steps_logged': 'Steps {action}: {steps} steps',
      'steps_updated': 'updated',
      'steps_saved': 'logged',
      'update': 'Update',
      'assigned_to_id': 'Assigned to ID',
      'target': 'Target',
      'weight': 'Weight',
      'kg': 'kg',
      'actual_results': 'Actual Results',
      'set': 'Set',
      'reps': 'reps',

      // Exercise Names - Chest
      'exercise_pushups': 'Push-ups',
      'exercise_bench_press': 'Bench Press',
      'exercise_dumbbell_flyes': 'Dumbbell Flyes',
      'exercise_incline_bench_press': 'Incline Bench Press',
      'exercise_decline_bench_press': 'Decline Bench Press',
      'exercise_cable_flyes': 'Cable Flyes',
      'exercise_chest_dips': 'Chest Dips',
      'exercise_incline_dumbbell_press': 'Incline Dumbbell Press',

      // Exercise Names - Legs
      'exercise_squats': 'Squats',
      'exercise_lunges': 'Lunges',
      'exercise_deadlifts': 'Deadlifts',
      'exercise_leg_press': 'Leg Press',
      'exercise_leg_curls': 'Leg Curls',
      'exercise_leg_extensions': 'Leg Extensions',
      'exercise_romanian_deadlifts': 'Romanian Deadlifts',
      'exercise_bulgarian_split_squats': 'Bulgarian Split Squats',
      'exercise_calf_raises': 'Calf Raises',
      'exercise_front_squats': 'Front Squats',

      // Exercise Names - Back
      'exercise_pullups': 'Pull-ups',
      'exercise_bentover_rows': 'Bent-over Rows',
      'exercise_lat_pulldown': 'Lat Pulldown',
      'exercise_seated_cable_row': 'Seated Cable Row',
      'exercise_tbar_row': 'T-Bar Row',
      'exercise_single_arm_dumbbell_row': 'Single-Arm Dumbbell Row',
      'exercise_face_pulls': 'Face Pulls',
      'exercise_chinups': 'Chin-ups',
      'exercise_inverted_rows': 'Inverted Rows',
      'exercise_hyperextensions': 'Hyperextensions',

      // Exercise Names - Shoulders
      'exercise_overhead_press': 'Overhead Press',
      'exercise_lateral_raises': 'Lateral Raises',
      'exercise_front_raises': 'Front Raises',
      'exercise_rear_delt_flyes': 'Rear Delt Flyes',
      'exercise_arnold_press': 'Arnold Press',
      'exercise_upright_rows': 'Upright Rows',
      'exercise_shrugs': 'Shrugs',

      // Exercise Names - Arms
      'exercise_barbell_curls': 'Barbell Curls',
      'exercise_dumbbell_curls': 'Dumbbell Curls',
      'exercise_hammer_curls': 'Hammer Curls',
      'exercise_preacher_curls': 'Preacher Curls',
      'exercise_concentration_curls': 'Concentration Curls',
      'exercise_cable_curls': 'Cable Curls',
      'exercise_tricep_dips': 'Tricep Dips',
      'exercise_tricep_pushdowns': 'Tricep Pushdowns',
      'exercise_overhead_tricep_extension': 'Overhead Tricep Extension',
      'exercise_close_grip_bench': 'Close-Grip Bench Press',
      'exercise_skull_crushers': 'Skull Crushers',
      'exercise_tricep_kickbacks': 'Tricep Kickbacks',

      // Exercise Names - Core
      'exercise_plank': 'Plank',
      'exercise_crunches': 'Crunches',
      'exercise_russian_twists': 'Russian Twists',
      'exercise_bicycle_crunches': 'Bicycle Crunches',
      'exercise_leg_raises': 'Leg Raises',
      'exercise_hanging_leg_raises': 'Hanging Leg Raises',
      'exercise_side_plank': 'Side Plank',
      'exercise_ab_wheel_rollout': 'Ab Wheel Rollout',
      'exercise_dead_bug': 'Dead Bug',
      'exercise_bird_dog': 'Bird Dog',
      'exercise_mountain_climbers': 'Mountain Climbers',

      // Exercise Names - Cardio
      'exercise_jumping_jacks': 'Jumping Jacks',
      'exercise_burpees': 'Burpees',
      'exercise_running': 'Running',
      'exercise_cycling': 'Cycling',
      'exercise_rowing': 'Rowing',
      'exercise_jump_rope': 'Jump Rope',
      'exercise_box_jumps': 'Box Jumps',
      'exercise_high_knees': 'High Knees',
      'exercise_butt_kicks': 'Butt Kicks',
      'exercise_sprints': 'Sprints',
      'exercise_stair_climbing': 'Stair Climbing',
      'exercise_elliptical': 'Elliptical',
      'exercise_swimming': 'Swimming',

      // Exercise Names - Full Body
      'exercise_kettlebell_swings': 'Kettlebell Swings',
      'exercise_clean_and_press': 'Clean and Press',
      'exercise_thrusters': 'Thrusters',
      'exercise_wall_balls': 'Wall Balls',
      'exercise_turkish_getups': 'Turkish Get-ups',
      'exercise_battle_ropes': 'Battle Ropes',
      'exercise_farmers_walk': 'Farmer\'s Walk',
      'exercise_sled_push': 'Sled Push',
      'exercise_sled_pull': 'Sled Pull',
      'exercise_medicine_ball_slams': 'Medicine Ball Slams',

      // Workout Creation Wizard
      'create_workout_wizard': 'Create Workout',
      'edit_workout': 'Edit Workout',
      'step': 'Step',
      'of': 'of',
      'basic_information': 'Basic Information',
      'trainee_selection': 'Trainee Selection',
      'exercise_selection': 'Exercise Selection',
      'review_create': 'Review & Create',
      'workout_name': 'Workout Name',
      'enter_workout_name': 'Enter workout name',
      'description': 'Description',
      'workout_description': 'Workout description',
      'select_date': 'Select Date',
      'estimated_duration': 'Estimated Duration (minutes)',
      'difficulty': 'Difficulty',
      'recurrence': 'Recurrence',
      'single_workout': 'Single Workout',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'recurrence_count': 'Number of occurrences',
      'next': 'Next',
      'previous': 'Previous',
      'please_enter_workout_name': 'Please enter a workout name',
      'please_enter_description': 'Please enter a description',
      'select_trainees': 'Select Trainees',
      'please_select_trainee': 'Please select at least one trainee',
      'exercises': 'Exercises',
      'add_from_library': 'Add from Library',
      'create_custom_exercise': 'Create Custom Exercise',
      'please_add_exercise': 'Please add at least one exercise',
      'drag_to_reorder': 'Drag to reorder exercises',
      'exercise_library': 'Exercise Library',
      'search_exercises': 'Search exercises...',
      'filter_by_category': 'Filter by Category',
      'all_categories': 'All Categories',
      'filter_by_muscle': 'Filter by Muscle',
      'all_muscles': 'All Muscles',
      'filter_by_equipment': 'Filter by Equipment',
      'all_equipment': 'All Equipment',
      'configure': 'Configure',
      'remove': 'Remove',
      'review_workout': 'Review Workout',
      'workout_details': 'Workout Details',
      'difficulty_level': 'Difficulty Level',
      'scheduled_date': 'Scheduled Date',
      'recurrence_pattern': 'Recurrence Pattern',
      'selected_trainees': 'Selected Trainees',
      'trainees_selected': 'Trainees: {count} selected',
      'emails': 'Emails',
      'none_selected': 'None selected',
      'exercises_count': 'Exercises ({count})',
      'trainer_notes': 'Trainer Notes',
      'optional_notes': 'Optional notes for trainees...',
      'create_workout_button': 'Create Workout',
      'update_workout': 'Update Workout',
      'creating_workout': 'Creating workout...',
      'updating_workout': 'Updating workout...',
      'workout_created_successfully': 'Workout created successfully!',
      'workout_updated_successfully': 'Workout updated successfully!',
      'configure_exercise': 'Configure Exercise',
      'sets': 'Sets',
      'number_of_sets': 'Number of sets',
      'reps_per_set': 'Reps per set',
      'weight_kg': 'Weight (kg)',
      'optional': 'Optional',
      'please_enter_sets': 'Please enter number of sets',
      'please_enter_reps': 'Please enter reps per set',
      'custom_exercise': 'Custom Exercise',
      'exercise_name': 'Exercise Name',
      'enter_exercise_name': 'Enter exercise name',
      'instructions': 'Instructions',
      'exercise_instructions': 'Exercise instructions',
      'please_enter_exercise_name': 'Please enter exercise name',
      'please_enter_instructions': 'Please enter instructions',

      // Recipe Names (Nutrition)
      'recipe_grilled_chicken_salad': 'Grilled Chicken Salad',
      'recipe_protein_smoothie': 'Protein Smoothie',
      'recipe_oatmeal_with_fruits': 'Oatmeal with Fruits',
      'recipe_salmon_with_vegetables': 'Salmon with Vegetables',
      'recipe_greek_yogurt_parfait': 'Greek Yogurt Parfait',
      'recipe_quinoa_bowl': 'Quinoa Bowl',
      'recipe_turkey_wrap': 'Turkey Wrap',
      'recipe_protein_pancakes': 'Protein Pancakes',
      'recipe_tuna_salad': 'Tuna Salad',
      'recipe_chicken_stir_fry': 'Chicken Stir Fry',

      // Goal Types
      'goal_type_weight_loss': 'Weight Loss',
      'goal_type_muscle_gain': 'Muscle Gain',
      'goal_type_endurance': 'Endurance',
      'goal_type_strength': 'Strength',
      'goal_type_flexibility': 'Flexibility',
      'goal_type_body_fat': 'Body Fat Reduction',
      'goal_type_performance': 'Performance',

      // Additional Dialog/UI Text
      'id': 'ID',
      'type': 'Type',
      'current': 'Current',
      'coming_soon': 'coming soon!',
      'add_trainee_feature': 'Add trainee feature',
      'schedule_workout_feature': 'Schedule workout feature',
      'create_meal_plan_feature': 'Create meal plan feature',
      'nutrition_library_feature': 'Nutrition library feature',
      'no_trainees_available': 'No trainees available',
      'system_has_mock_trainees': 'The system has mock trainees, but they may not be loaded.',
      'error': 'Error',
      'error_loading_data': 'Error loading data',
      'error_creating_workout': 'Error creating workout',
      'error_creating_goal': 'Error creating goal',
      'invalid_workout_mode': 'Invalid workout creation mode',
      'custom_workout_created': 'Custom workout "{name}" created for {trainee}!',
      'workout_created_for': 'Workout "{name}" created for {trainee}!',
      'goal_created_for': 'Goal "{name}" created for {trainee}!',
      'goal_deleted': 'Goal "{name}" deleted',
      'workout_updated': 'Workout "{name}" updated',
      'updated_workouts_in_series': 'Updated {count} workouts in the series',
      'test_workout_created': 'Test workout created for Mike Johnson! Now login as Mike to see it.',
      'error_creating_test_workout': 'Error creating test workout',
      'select_trainee_to_create_workout_for': 'Select a trainee to create a workout for:',
      'select_trainee_to_create_goal_for': 'Select a trainee to create a goal for:',
      'use_template_colon': 'Use Template: {name}',
      'are_you_sure_delete': 'Are you sure you want to delete "{name}"?',
      'progress_percentage': 'Progress: {percent}%',
      'progress_charts_would_show': 'Progress charts and statistics would be shown here.',
      'assigned_to_colon': 'Assigned to: {name} ({id})',
      'type_colon': 'Type: {type}',
      'current_colon': 'Current: {value} {unit}',
      'target_colon': 'Target: {value} {unit}',
      'deadline_colon': 'Deadline: {date}',
      'id_colon': 'ID: {id}',
      'copy_suffix': ' (Copy)',
      'workout_duplicated_as': 'Workout duplicated as "{name}"',
      'confirm_deletion': 'Confirm Deletion',
      'action_cannot_undone': 'This action cannot be undone.',
      'delete_all': 'Delete All',
      'deleted_workouts_from_series': 'Deleted {count} workouts from the series',
      'progress_report_only_completed': 'Progress report is only available for completed workouts',
      'trainee_not_found': 'Trainee not found',
      'email_colon': 'Email: {email}',
      'id_display': 'ID: {id}',
      'role_colon': 'Role: {role}',
      'description_colon': 'Description: {description}',
      'difficulty_colon': 'Difficulty: {difficulty}',
      'duration_colon': 'Duration: {duration} minutes',
      'scheduled_colon': 'Scheduled: {date}',
      'status_completed': 'Status: ✅ Completed',
      'status_pending': 'Status: ⏳ Pending',
      'status_in_progress': 'Status: ⏳ In Progress',
      'completed_at_colon': 'Completed: {date}',
      'proposed_effort': 'Proposed Effort:',
      'set_with_number': 'Set {number}: {reps} reps, {kg} kg',
      'notes_colon': 'Notes:',
      'name_progress': '{name} Progress',
      'workout_completion_rate': 'Workout completion rate',
      'strength_progression': 'Strength progression',
      'weight_changes': 'Weight changes',
      'goal_achievements': 'Goal achievements',
      'create_workout_button': 'Create Workout',
      'are_you_sure_delete_workouts': 'Are you sure you want to delete all {count} workouts in this recurring series?',
      'are_you_sure_delete_workout': 'Are you sure you want to delete "{name}"?',
      'create_meal_plan_feature': 'Create meal plan feature',
      'nutrition_library_feature': 'Nutrition library feature',
      'notification_completed_workout': '{name} completed "{workout}"',
      'notification_time_ago': '{time} hours ago',
      'notification_new_message': 'New message from {name}',
      'notification_asked_about': 'Asked about rest days',
      'notification_missed_workout': '{name} missed yesterday\'s workout',
      'notification_consider_followup': 'Consider following up',
      'assigned_workouts_count': 'Assigned workouts: {count}',
      'completed_workouts_count': 'Completed: {count}',
      'no_trainees_available_message': 'No trainees available.',
      'select_trainee_for_template': 'Select a trainee to create this workout for:',
      'select_this_trainee': 'Select this trainee',
      'error_with_message': 'Error: {message}',
      'status_completed_checkmark': '✅ Completed',
      'status_in_progress_clock': '⏳ In Progress',
      'no_exercises_added': 'No exercises added yet',
      'tap_add_to_start': 'Tap "Add Exercise" to get started',
      'tips_label': 'Tips:',
      'minutes_label': 'minutes',
      'day_label': 'day',
      'days_label': 'days',
      'edit_exercise_title': 'Edit {name}',
      'unknown_trainee': 'Unknown',
      'choose_workout_creation': 'Choose how you want to create your workout:',
      'create_from_scratch': 'Create from Scratch',
      'build_custom_workout': 'Build a custom workout by selecting exercises manually',
      'use_workout_template': 'Use Workout Template',
      'start_with_prebuilt': 'Start with a pre-built workout plan',
      'use_selected_template': 'Use Selected Template',
      'no_templates_available': 'No templates available',
      'loading_templates': 'Loading templates...',
      'exercises_count': '{count} exercises',
      'add_exercises_count': 'Add Exercises ({count})',
      'select_trainees': 'Select Trainees',
      'review_workout': 'Review Workout',
      'assigned_to': 'Assigned To',
      'category_label': 'Category',
      'difficulty_level': 'Difficulty Level',
      'duration_label': 'Duration',
      'scheduled_label': 'Scheduled',
      'recurrence_label': 'Recurrence',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'none': 'None',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'repeat_for_weeks': 'Repeat for (weeks)',
      'repeat_for_months': 'Repeat for (months)',
      'repeat_for_days': 'Repeat for (days)',
      'recurrence_summary': 'Recurrence Summary',
      'total_workouts_to_create': 'Total workouts to create',
      'trainee_singular': 'trainee',
      'trainees_plural': 'trainees',
      'occurrence_singular': 'occurrence',
      'occurrences_plural': 'occurrences',
      'daily_for_days': 'Daily for {count} day{s}',
      'weekly_for_weeks': 'Weekly for {count} week{s}',
      'monthly_for_months': 'Monthly for {count} month{s}',
      'trainees': 'Trainees',
      'emails': 'Emails',
      'none_selected': 'None selected',
      'exercises_with_count': 'Exercises ({count})',
    },
    'ro': {
      // Common
      'app_name': 'Platformă de Antrenament Fitness',
      'loading': 'Se încarcă...',
      'save': 'Salvează',
      'save_changes': 'Salvează Modificările',
      'cancel': 'Anulează',
      'delete': 'Șterge',
      'edit': 'Editează',
      'add': 'Adaugă',
      'close': 'Închide',
      'create': 'Creează',
      'update': 'Actualizează',
      'confirm': 'Confirmă',
      'error': 'Eroare',
      'success': 'Succes',
      'warning': 'Avertisment',
      'search': 'Caută',
      'filter': 'Filtrează',
      'clear': 'Curăță',
      'select': 'Selectează',
      'none': 'Niciunul',
      'all': 'Toate',
      'refresh': 'Reîmprospătează',
      'logout': 'Deconectare',
      'notifications': 'Notificări',
      'settings': 'Setări',
      'templates': 'Șabloane',
      'library': 'Bibliotecă',
      'new_workout': 'Antrenament Nou',
      'view': 'Vezi',
      'details': 'Detalii',
      'assigned': 'Atribuit',
      'completed': 'Finalizat',
      'pending': 'În Așteptare',
      'no_data_available': 'Nu există date disponibile',
      'assigned_to': 'Atribuit lui',
      'created_by': 'Creat de',
      'created_at': 'Creat la',
      'due_date': 'Termen Limită',
      'start_date': 'Data Start',
      'end_date': 'Data Sfârșit',

      // Auth
      'login': 'Autentificare',
      'register': 'Înregistrare',
      'email': 'Email',
      'password': 'Parolă',
      'name': 'Nume',
      'confirm_password': 'Confirmă Parola',
      'login_button': 'Intră în cont',
      'register_button': 'Înregistrează-te',
      'have_account': 'Ai deja un cont?',
      'no_account': 'Nu ai un cont?',
      'login_link': 'Autentifică-te aici',
      'register_link': 'Înregistrează-te aici',
      'welcome_back': 'Bine ai revenit',
      'create_account': 'Creează cont',

      // Dashboard
      'dashboard': 'Panou de control',
      'admin_dashboard': 'Panou Administrator',
      'trainer_dashboard': 'Panou Antrenor',
      'trainee_dashboard': 'Panou Antrenat',

      // Tabs
      'trainees': 'Antrenați',
      'workouts': 'Antrenamente',
      'assigned_workouts': 'Antrenamente Atribuite',
      'goals': 'Obiective',
      'assigned_goals': 'Obiective Atribuite',
      'nutrition': 'Nutriție',
      'assigned_nutrition': 'Plan Nutrițional Atribuit',
      'progress': 'Progres',

      // Users
      'users': 'Utilizatori',
      'add_user': 'Adaugă Utilizator',
      'edit_user': 'Editează Utilizator',
      'user_type': 'Tip Utilizator',
      'trainer': 'Antrenor',
      'trainee': 'Antrenat',
      'admin': 'Administrator',
      'assign_trainer': 'Atribuie Antrenor',
      'select_trainer': 'Selectează Antrenor',
      'no_trainer': 'Fără Antrenor',

      // Workouts
      'create_workout': 'Creează Antrenament',
      'workout_name': 'Nume Antrenament',
      'workout_date': 'Data Antrenament',
      'exercises': 'Exerciții',
      'add_exercise': 'Adaugă Exercițiu',
      'exercise_name': 'Nume Exercițiu',
      'sets': 'Serii',
      'reps': 'Repetări',
      'weight': 'Greutate',
      'duration': 'Durată',
      'distance': 'Distanță',
      'rest_time': 'Timp Odihnă',
      'difficulty': 'Dificultate',
      'beginner': 'Începător',
      'intermediate': 'Intermediar',
      'advanced': 'Avansat',
      'category': 'Categorie',
      'strength': 'Forță',
      'cardio': 'Cardio',
      'flexibility': 'Flexibilitate',
      'equipment': 'Echipament',
      'bodyweight': 'Greutate corporală',
      'barbell': 'Bară',
      'dumbbell': 'Ganteră',
      'machine': 'Mașină',
      'cable': 'Cablu',

      // Nutrition
      'nutrition_plan': 'Plan Nutrițional',
      'assign_nutrition': 'Atribuie Nutriție',
      'daily_calories': 'Calorii Zilnice',
      'daily_caloric_target': 'Țintă Calorică Zilnică',
      'daily_caloric_limit': 'Limită Calorică Zilnică',
      'recipe_ideas': 'Idei de Rețete',
      'recipes': 'Rețete',
      'ingredients': 'Ingrediente',
      'instructions': 'Instrucțiuni',
      'calories': 'Calorii',
      'log_food': 'Înregistrează Alimentație',
      'food_name': 'Nume Aliment',
      'food_log': 'Jurnal Alimentar',
      'view_food_log': 'Vezi Jurnal Alimentar',
      'consumed': 'Consumat',
      'target': 'Țintă',
      'remaining': 'Rămas',
      'exceeded': 'Depășit',
      'todays_food_log': 'Jurnalul Alimentar de Astăzi',
      'logged_food_items': 'Alimente Înregistrate',
      'no_food_logged': 'Niciun aliment înregistrat pentru această dată',
      'add_item': 'Adaugă Element',

      // Goals
      'create_goal': 'Creează Obiectiv',
      'goal_name': 'Nume Obiectiv',
      'goal_type': 'Tip Obiectiv',
      'target_value': 'Valoare Țintă',
      'current_value': 'Valoare Curentă',
      'deadline': 'Termen Limită',
      'status': 'Status',
      'pending': 'În Așteptare',
      'in_progress': 'În Progres',
      'completed': 'Finalizat',

      // Progress
      'view_progress': 'Vezi Progres',
      'body_measurements': 'Măsurători Corporale',
      'weight': 'Greutate',
      'height': 'Înălțime',
      'body_fat': 'Grăsime Corporală',
      'muscle_mass': 'Masă Musculară',
      'date': 'Data',

      // Messages
      'no_data': 'Nu există date disponibile',
      'no_trainees': 'Nu există antrenați disponibili',
      'no_workouts': 'Nu există antrenamente atribuite',
      'no_goals': 'Nu există obiective atribuite',
      'no_nutrition_plan': 'Nu există plan nutrițional atribuit',
      'error_loading_data': 'Eroare la încărcarea datelor',
      'success_create': 'Creat cu succes',
      'success_update': 'Actualizat cu succes',
      'success_delete': 'Șters cu succes',
      'confirm_delete': 'Sigur vrei să ștergi?',

      // Tooltips
      'tooltip_create_workout': 'Creează Antrenament',
      'tooltip_assign_nutrition': 'Atribuie Nutriție',
      'tooltip_create_goal': 'Creează Obiectiv',
      'tooltip_view_progress': 'Vezi Progres',
      'tooltip_view_food_log': 'Vezi Jurnal Alimentar',

      // Buttons
      'new_workout': 'Antrenament Nou',
      'add_trainee': 'Adaugă Antrenat',
      'template': 'Șablon',
      'schedule': 'Programează',
      'test': 'Testează',
      'create_goal': 'Creează Obiectiv',
      'view_food_log': 'Vezi Jurnal Alimentar',
      'duplicate': 'Duplică',
      'view_details': 'Vezi Detalii',
      'progress_report': 'Raport Progres',

      // Messages
      'found_trainees': 'Am găsit {count} antrenați atribuiți',
      'no_trainees_yet': 'Încă niciun antrenat',
      'trainees_appear_here': 'Antrenații vor apărea aici când îți vor fi atribuiți',
      'workouts_assigned_completed': 'Antrenamente: {assigned} atribuite, {completed} finalizate',
      'create_workout': 'Creează Antrenament',
      'assign_nutrition': 'Atribuie Nutriție',
      'created_workouts_total': 'Total {count} antrenamente create',
      'no_workouts_created_yet': 'Încă niciun antrenament creat',
      'create_first_workout': 'Creează primul antrenament folosind butonul + sau butonul Testează',
      'exercises_duration': '{exercises} exerciții • {duration} min',
      'scheduled': 'Programat',
      'created_goals_total': 'Total {count} obiective create',
      'no_goals_created_yet': 'Încă niciun obiectiv creat',
      'create_first_goal': 'Creează primul obiectiv folosind butonul Creează Obiectiv',
      'progress': 'Progres',
      'deadline_days_remaining': 'Termen: {days} zile rămase',
      'deadline_overdue': 'Termen: Depășit',
      'assigned_nutrition_plans_count': 'Planuri Nutriționale Atribuite ({count})',
      'no_nutrition_plans_assigned': 'Niciun Plan Nutrițional Atribuit',
      'assign_plans_from_trainees_tab': 'Atribuie planuri nutriționale antrenațiilor din tab-ul Antrenați',
      'unknown_trainee': 'Antrenat Necunoscut',
      'kcal_per_day': '{calories} kcal/zi',
      'recipes_count': '{count} rețete',
      'created': 'Creat',

      // Dialogs
      'logout': 'Deconectare',
      'are_you_sure_logout': 'Sigur vrei să te deconectezi?',
      'confirm_delete': 'Sigur vrei să ștergi?',
      'delete_goal': 'Șterge Obiectiv',
      'delete_workout': 'Șterge Antrenament',
      'notifications': 'Notificări',
      'create_new_workout': 'Creează Antrenament Nou',
      'select_trainee': 'Selectează Antrenat',
      'select_trainee_to_create_workout': 'Selectează un antrenat pentru care să creezi un antrenament:',
      'use_template': 'Folosește Șablon',
      'select_trainee_to_create_this_workout': 'Selectează un antrenat pentru care să creezi acest antrenament:',
      'trainee_progress': 'Progresul lui {name}',
      'progress_charts_shown': 'Aici vor fi afișate grafice și statistici de progres.',
      'workout_completion_rate': 'Rata de finalizare a antrenamentelor',
      'strength_progression': 'Progresia forței',
      'weight_changes': 'Modificări greutate',
      'goal_achievements': 'Realizări obiective',
      'workout_statistics': 'Statistici Antrenamente',
      'assigned_workouts': 'Antrenamente atribuite',
      'member_since': 'Membru din',

      // Trainee Dashboard
      'my_user_id': 'ID-ul Meu',
      'my_name': 'Numele Meu',
      'my_email': 'Email-ul Meu',
      'workouts_found': 'Antrenamente găsite',
      'refresh_debug': 'Reîmprospătează & Debug',
      'no_workouts_assigned_yet': 'Încă niciun antrenament atribuit',
      'trainer_will_assign_soon': 'Antrenorul tău îți va atribui antrenamente în curând',
      'use_refresh_button': 'Folosește butonul Reîmprospătează de mai sus pentru a verifica antrenamente noi',
      'edit_results': 'Editează Rezultate',
      'start_workout': 'Începe Antrenament',
      'continue_workout': 'Continuă Antrenament',
      'notes': 'Notițe',
      'log_food_intake': 'Înregistrează Alimentație',
      'update_todays_steps': 'Actualizează Pașii de Astăzi',
      'log_steps_manually': 'Înregistrează Pașii Manual',
      'enter_step_count': 'Introdu numărul de pași',
      'please_enter_step_count': 'Te rog introdu numărul de pași',
      'please_enter_valid_number': 'Te rog introdu un număr valid',
      'steps_logged': 'Pași {action}: {steps} pași',
      'steps_updated': 'actualizați',
      'steps_saved': 'înregistrați',
      'update': 'Actualizează',
      'assigned_to_id': 'Atribuit ID-ului',
      'target': 'Țintă',
      'weight': 'Greutate',
      'kg': 'kg',
      'actual_results': 'Rezultate Reale',
      'set': 'Seria',
      'reps': 'repetări',

      // Exercise Names - Chest (Piept)
      'exercise_pushups': 'Flotări',
      'exercise_bench_press': 'Împins Bancă',
      'exercise_dumbbell_flyes': 'Fluturări cu Gantere',
      'exercise_incline_bench_press': 'Împins Bancă Înclinată',
      'exercise_decline_bench_press': 'Împins Bancă Declinată',
      'exercise_cable_flyes': 'Fluturări la Scripete',
      'exercise_chest_dips': 'Fonduri pentru Piept',
      'exercise_incline_dumbbell_press': 'Împins Gantere Înclinat',

      // Exercise Names - Legs (Picioare)
      'exercise_squats': 'Genuflexiuni',
      'exercise_lunges': 'Pași Lungi',
      'exercise_deadlifts': 'Îndrepții',
      'exercise_leg_press': 'Presă Picioare',
      'exercise_leg_curls': 'Flexii Picioare',
      'exercise_leg_extensions': 'Extensii Picioare',
      'exercise_romanian_deadlifts': 'Îndrepții Românești',
      'exercise_bulgarian_split_squats': 'Genuflexiuni Bulgărești',
      'exercise_calf_raises': 'Ridicări pe Vârfuri',
      'exercise_front_squats': 'Genuflexiuni Frontale',

      // Exercise Names - Back (Spate)
      'exercise_pullups': 'Tracțiuni',
      'exercise_bentover_rows': 'Rânduri Aplecate',
      'exercise_lat_pulldown': 'Trageri la Lat',
      'exercise_seated_cable_row': 'Rânduri la Scripete Așezat',
      'exercise_tbar_row': 'Rânduri T-Bar',
      'exercise_single_arm_dumbbell_row': 'Rânduri cu o Ganteră',
      'exercise_face_pulls': 'Trageri la Față',
      'exercise_chinups': 'Tracțiuni Supinație',
      'exercise_inverted_rows': 'Rânduri Inversate',
      'exercise_hyperextensions': 'Hiperextensii',

      // Exercise Names - Shoulders (Umeri)
      'exercise_overhead_press': 'Împins deasupra Capului',
      'exercise_lateral_raises': 'Ridicări Laterale',
      'exercise_front_raises': 'Ridicări Frontale',
      'exercise_rear_delt_flyes': 'Fluturări Deltoizi Posteriori',
      'exercise_arnold_press': 'Împins Arnold',
      'exercise_upright_rows': 'Rânduri Verticale',
      'exercise_shrugs': 'Ridicări Umeri',

      // Exercise Names - Arms (Brațe)
      'exercise_barbell_curls': 'Flexii cu Bară',
      'exercise_dumbbell_curls': 'Flexii cu Gantere',
      'exercise_hammer_curls': 'Flexii Ciocan',
      'exercise_preacher_curls': 'Flexii la Pupitru',
      'exercise_concentration_curls': 'Flexii de Concentrare',
      'exercise_cable_curls': 'Flexii la Scripete',
      'exercise_tricep_dips': 'Fonduri Triceps',
      'exercise_tricep_pushdowns': 'Împingeri Triceps',
      'exercise_overhead_tricep_extension': 'Extensie Triceps deasupra Capului',
      'exercise_close_grip_bench': 'Împins Bancă Priză Strânsă',
      'exercise_skull_crushers': 'Zdrobitori de Craniu',
      'exercise_tricep_kickbacks': 'Retrași Triceps',

      // Exercise Names - Core (Abdomen)
      'exercise_plank': 'Plank',
      'exercise_crunches': 'Abdomene',
      'exercise_russian_twists': 'Rotații Rusești',
      'exercise_bicycle_crunches': 'Abdomene Bicicletă',
      'exercise_leg_raises': 'Ridicări Picioare',
      'exercise_hanging_leg_raises': 'Ridicări Picioare Atârnate',
      'exercise_side_plank': 'Plank Lateral',
      'exercise_ab_wheel_rollout': 'Rulări cu Roata Abdominală',
      'exercise_dead_bug': 'Gândac Mort',
      'exercise_bird_dog': 'Câine-Pasăre',
      'exercise_mountain_climbers': 'Alpiniști',

      // Exercise Names - Cardio
      'exercise_jumping_jacks': 'Sărituri Stea',
      'exercise_burpees': 'Burpees',
      'exercise_running': 'Alergare',
      'exercise_cycling': 'Ciclism',
      'exercise_rowing': 'Vâslit',
      'exercise_jump_rope': 'Sărit Coarda',
      'exercise_box_jumps': 'Sărituri pe Cutie',
      'exercise_high_knees': 'Genunchi Sus',
      'exercise_butt_kicks': 'Lovituri Călcâie',
      'exercise_sprints': 'Sprinturi',
      'exercise_stair_climbing': 'Urcat Scări',
      'exercise_elliptical': 'Eliptică',
      'exercise_swimming': 'Înot',

      // Exercise Names - Full Body (Corp Complet)
      'exercise_kettlebell_swings': 'Legănări Kettlebell',
      'exercise_clean_and_press': 'Smuls și Împins',
      'exercise_thrusters': 'Thrusters',
      'exercise_wall_balls': 'Mingi la Perete',
      'exercise_turkish_getups': 'Ridicări Turcești',
      'exercise_battle_ropes': 'Frânghii de Luptă',
      'exercise_farmers_walk': 'Plimbare Țăranului',
      'exercise_sled_push': 'Împingere Sanie',
      'exercise_sled_pull': 'Tragere Sanie',
      'exercise_medicine_ball_slams': 'Loviri cu Minge Medicinală',

      // Workout Creation Wizard
      'create_workout_wizard': 'Creează Antrenament',
      'edit_workout': 'Editează Antrenament',
      'step': 'Pasul',
      'of': 'din',
      'basic_information': 'Informații de Bază',
      'trainee_selection': 'Selectare Antrenați',
      'exercise_selection': 'Selectare Exerciții',
      'review_create': 'Revizuire & Creare',
      'workout_name': 'Nume Antrenament',
      'enter_workout_name': 'Introdu numele antrenamentului',
      'description': 'Descriere',
      'workout_description': 'Descrierea antrenamentului',
      'select_date': 'Selectează Data',
      'estimated_duration': 'Durată Estimată (minute)',
      'difficulty': 'Dificultate',
      'recurrence': 'Recurență',
      'single_workout': 'Antrenament Unic',
      'daily': 'Zilnic',
      'weekly': 'Săptămânal',
      'recurrence_count': 'Număr de apariții',
      'next': 'Următorul',
      'previous': 'Anterior',
      'please_enter_workout_name': 'Te rog introdu numele antrenamentului',
      'please_enter_description': 'Te rog introdu o descriere',
      'select_trainees': 'Selectează Antrenați',
      'please_select_trainee': 'Te rog selectează cel puțin un antrenat',
      'exercises': 'Exerciții',
      'add_from_library': 'Adaugă din Bibliotecă',
      'create_custom_exercise': 'Creează Exercițiu Personalizat',
      'please_add_exercise': 'Te rog adaugă cel puțin un exercițiu',
      'drag_to_reorder': 'Trage pentru a reordona exercițiile',
      'exercise_library': 'Bibliotecă Exerciții',
      'search_exercises': 'Caută exerciții...',
      'filter_by_category': 'Filtrează după Categorie',
      'all_categories': 'Toate Categoriile',
      'filter_by_muscle': 'Filtrează după Mușchi',
      'all_muscles': 'Toți Mușchii',
      'filter_by_equipment': 'Filtrează după Echipament',
      'all_equipment': 'Tot Echipamentul',
      'configure': 'Configurează',
      'remove': 'Elimină',
      'review_workout': 'Revizuire Antrenament',
      'workout_details': 'Detalii Antrenament',
      'difficulty_level': 'Nivel Dificultate',
      'scheduled_date': 'Data Programată',
      'recurrence_pattern': 'Pattern Recurență',
      'selected_trainees': 'Antrenați Selectați',
      'trainees_selected': 'Antrenați: {count} selectați',
      'emails': 'Email-uri',
      'none_selected': 'Niciunul selectat',
      'exercises_count': 'Exerciții ({count})',
      'trainer_notes': 'Notițe Antrenor',
      'optional_notes': 'Notițe opționale pentru antrenați...',
      'create_workout_button': 'Creează Antrenament',
      'update_workout': 'Actualizează Antrenament',
      'creating_workout': 'Se creează antrenamentul...',
      'updating_workout': 'Se actualizează antrenamentul...',
      'workout_created_successfully': 'Antrenament creat cu succes!',
      'workout_updated_successfully': 'Antrenament actualizat cu succes!',
      'configure_exercise': 'Configurează Exercițiu',
      'sets': 'Serii',
      'number_of_sets': 'Număr de serii',
      'reps_per_set': 'Repetări pe serie',
      'weight_kg': 'Greutate (kg)',
      'optional': 'Opțional',
      'please_enter_sets': 'Te rog introdu numărul de serii',
      'please_enter_reps': 'Te rog introdu repetările pe serie',
      'custom_exercise': 'Exercițiu Personalizat',
      'exercise_name': 'Nume Exercițiu',
      'enter_exercise_name': 'Introdu numele exercițiului',
      'instructions': 'Instrucțiuni',
      'exercise_instructions': 'Instrucțiunile exercițiului',
      'please_enter_exercise_name': 'Te rog introdu numele exercițiului',
      'please_enter_instructions': 'Te rog introdu instrucțiunile',

      // Recipe Names (Nutrition)
      'recipe_grilled_chicken_salad': 'Salată cu Pui la Grătar',
      'recipe_protein_smoothie': 'Smoothie Proteic',
      'recipe_oatmeal_with_fruits': 'Ovăz cu Fructe',
      'recipe_salmon_with_vegetables': 'Somon cu Legume',
      'recipe_greek_yogurt_parfait': 'Parfait cu Iaurt Grecesc',
      'recipe_quinoa_bowl': 'Bowl cu Quinoa',
      'recipe_turkey_wrap': 'Wrap cu Curcan',
      'recipe_protein_pancakes': 'Clătite Proteice',
      'recipe_tuna_salad': 'Salată cu Ton',
      'recipe_chicken_stir_fry': 'Pui Stir Fry',

      // Goal Types
      'goal_type_weight_loss': 'Pierdere în Greutate',
      'goal_type_muscle_gain': 'Câștig de Masă Musculară',
      'goal_type_endurance': 'Rezistență',
      'goal_type_strength': 'Forță',
      'goal_type_flexibility': 'Flexibilitate',
      'goal_type_body_fat': 'Reducere Grăsime Corporală',
      'goal_type_performance': 'Performanță',

      // Additional Dialog/UI Text
      'id': 'ID',
      'type': 'Tip',
      'current': 'Curent',
      'coming_soon': 'în curând!',
      'add_trainee_feature': 'Funcția de adăugare antrenat',
      'schedule_workout_feature': 'Funcția de programare antrenament',
      'create_meal_plan_feature': 'Funcția de creare plan alimentar',
      'nutrition_library_feature': 'Funcția de bibliotecă nutriție',
      'no_trainees_available': 'Niciun antrenat disponibil',
      'system_has_mock_trainees': 'Sistemul are antrenați de test, dar s-ar putea să nu fie încărcați.',
      'error': 'Eroare',
      'error_loading_data': 'Eroare la încărcarea datelor',
      'error_creating_workout': 'Eroare la crearea antrenamentului',
      'error_creating_goal': 'Eroare la crearea obiectivului',
      'invalid_workout_mode': 'Mod invalid de creare antrenament',
      'custom_workout_created': 'Antrenament personalizat "{name}" creat pentru {trainee}!',
      'workout_created_for': 'Antrenament "{name}" creat pentru {trainee}!',
      'goal_created_for': 'Obiectiv "{name}" creat pentru {trainee}!',
      'goal_deleted': 'Obiectiv "{name}" șters',
      'workout_updated': 'Antrenament "{name}" actualizat',
      'updated_workouts_in_series': 'Actualizate {count} antrenamente în serie',
      'test_workout_created': 'Antrenament de test creat pentru Mike Johnson! Acum autentifică-te ca Mike pentru a-l vedea.',
      'error_creating_test_workout': 'Eroare la crearea antrenamentului de test',
      'select_trainee_to_create_workout_for': 'Selectează un antrenat pentru care să creezi un antrenament:',
      'select_trainee_to_create_goal_for': 'Selectează un antrenat pentru care să creezi un obiectiv:',
      'use_template_colon': 'Folosește Șablon: {name}',
      'are_you_sure_delete': 'Sigur vrei să ștergi "{name}"?',
      'progress_percentage': 'Progres: {percent}%',
      'progress_charts_would_show': 'Aici vor fi afișate grafice și statistici de progres.',
      'assigned_to_colon': 'Atribuit lui: {name} ({id})',
      'type_colon': 'Tip: {type}',
      'current_colon': 'Curent: {value} {unit}',
      'target_colon': 'Țintă: {value} {unit}',
      'deadline_colon': 'Termen: {date}',
      'id_colon': 'ID: {id}',
      'copy_suffix': ' (Copie)',
      'workout_duplicated_as': 'Antrenament duplicat ca "{name}"',
      'confirm_deletion': 'Confirmă Ștergerea',
      'action_cannot_undone': 'Această acțiune nu poate fi anulată.',
      'delete_all': 'Șterge Tot',
      'deleted_workouts_from_series': 'Șterse {count} antrenamente din serie',
      'progress_report_only_completed': 'Raportul de progres este disponibil doar pentru antrenamentele finalizate',
      'trainee_not_found': 'Antrenat negăsit',
      'email_colon': 'Email: {email}',
      'id_display': 'ID: {id}',
      'role_colon': 'Rol: {role}',
      'description_colon': 'Descriere: {description}',
      'difficulty_colon': 'Dificultate: {difficulty}',
      'duration_colon': 'Durată: {duration} minute',
      'scheduled_colon': 'Programat: {date}',
      'status_completed': 'Status: ✅ Finalizat',
      'status_pending': 'Status: ⏳ În Așteptare',
      'status_in_progress': 'Status: ⏳ În Desfășurare',
      'completed_at_colon': 'Finalizat: {date}',
      'proposed_effort': 'Efort Propus:',
      'set_with_number': 'Seria {number}: {reps} repetări, {kg} kg',
      'notes_colon': 'Notițe:',
      'name_progress': 'Progres {name}',
      'workout_completion_rate': 'Rată de finalizare antrenamente',
      'strength_progression': 'Progres forță',
      'weight_changes': 'Modificări greutate',
      'goal_achievements': 'Obiective atinse',
      'create_workout_button': 'Creează Antrenament',
      'are_you_sure_delete_workouts': 'Sigur vrei să ștergi toate cele {count} antrenamente din această serie recurentă?',
      'are_you_sure_delete_workout': 'Sigur vrei să ștergi "{name}"?',
      'create_meal_plan_feature': 'Funcție creare plan nutrițional',
      'nutrition_library_feature': 'Funcție bibliotecă nutrițională',
      'notification_completed_workout': '{name} a finalizat "{workout}"',
      'notification_time_ago': 'acum {time} ore',
      'notification_new_message': 'Mesaj nou de la {name}',
      'notification_asked_about': 'A întrebat despre zilele de odihnă',
      'notification_missed_workout': '{name} a ratat antrenamentul de ieri',
      'notification_consider_followup': 'Consideră să urmărești',
      'assigned_workouts_count': 'Antrenamente atribuite: {count}',
      'completed_workouts_count': 'Finalizate: {count}',
      'no_trainees_available_message': 'Niciun antrenat disponibil.',
      'select_trainee_for_template': 'Selectează un antrenat pentru care să creezi acest antrenament:',
      'select_this_trainee': 'Selectează acest antrenat',
      'error_with_message': 'Eroare: {message}',
      'status_completed_checkmark': '✅ Finalizat',
      'status_in_progress_clock': '⏳ În Desfășurare',
      'no_exercises_added': 'Niciun exercițiu adăugat încă',
      'tap_add_to_start': 'Apasă "Adaugă Exercițiu" pentru a începe',
      'tips_label': 'Sfaturi:',
      'minutes_label': 'minute',
      'day_label': 'zi',
      'days_label': 'zile',
      'edit_exercise_title': 'Editează {name}',
      'unknown_trainee': 'Necunoscut',
      'choose_workout_creation': 'Alege cum vrei să creezi antrenamentul:',
      'create_from_scratch': 'Creează de la Zero',
      'build_custom_workout': 'Construiește un antrenament personalizat selectând exerciții manual',
      'use_workout_template': 'Folosește Șablon Antrenament',
      'start_with_prebuilt': 'Începe cu un plan de antrenament pre-construit',
      'use_selected_template': 'Folosește Șablonul Selectat',
      'no_templates_available': 'Niciun șablon disponibil',
      'loading_templates': 'Se încarcă șabloanele...',
      'exercises_count': '{count} exerciții',
      'add_exercises_count': 'Adaugă Exerciții ({count})',
      'select_trainees': 'Selectează Antrenați',
      'review_workout': 'Revizuiește Antrenamentul',
      'assigned_to': 'Atribuit Către',
      'category_label': 'Categorie',
      'difficulty_level': 'Nivel Dificultate',
      'duration_label': 'Durată',
      'scheduled_label': 'Programat',
      'recurrence_label': 'Recurență',
      'beginner': 'Începător',
      'intermediate': 'Intermediar',
      'advanced': 'Avansat',
      'none': 'Niciunul',
      'daily': 'Zilnic',
      'weekly': 'Săptămânal',
      'monthly': 'Lunar',
      'repeat_for_weeks': 'Repetă pentru (săptămâni)',
      'repeat_for_months': 'Repetă pentru (luni)',
      'repeat_for_days': 'Repetă pentru (zile)',
      'recurrence_summary': 'Sumar Recurență',
      'total_workouts_to_create': 'Total antrenamente de creat',
      'trainee_singular': 'antrenat',
      'trainees_plural': 'antrenați',
      'occurrence_singular': 'apariție',
      'occurrences_plural': 'apariții',
      'daily_for_days': 'Zilnic pentru {count} zi{s}',
      'weekly_for_weeks': 'Săptămânal pentru {count} săptămân{s}',
      'monthly_for_months': 'Lunar pentru {count} lun{s}',
      'trainees': 'Antrenați',
      'emails': 'Email-uri',
      'none_selected': 'Niciunul selectat',
      'exercises_with_count': 'Exerciții ({count})',
    },
  };

  static String translate(String key, String languageCode, {Map<String, String>? params}) {
    var translation = _translations[languageCode]?[key] ?? _translations['en']?[key] ?? key;

    // Replace placeholders if params provided
    if (params != null) {
      params.forEach((key, value) {
        translation = translation.replaceAll('{$key}', value);
      });
    }

    return translation;
  }

  static Map<String, String> getTranslations(String languageCode) {
    return _translations[languageCode] ?? _translations['en']!;
  }

  static List<String> getSupportedLanguages() {
    return ['en', 'ro'];
  }

  static String getLanguageName(String code) {
    switch (code) {
      case 'en':
        return 'English';
      case 'ro':
        return 'Română';
      default:
        return code;
    }
  }

  /// Converts an English exercise name to its translation key
  static String _exerciseNameToKey(String englishName) {
    // Convert to lowercase and replace special characters
    String key = englishName.toLowerCase()
        .replaceAll('-', '')
        .replaceAll(' ', '_')
        .replaceAll('\'', '');
    return 'exercise_$key';
  }

  /// Gets a translated exercise name based on the English name
  static String translateExerciseName(String englishName, String languageCode) {
    final key = _exerciseNameToKey(englishName);
    return translate(key, languageCode) == key ? englishName : translate(key, languageCode);
  }

  /// Converts a recipe name to its translation key
  static String _recipeNameToKey(String englishName) {
    String key = englishName.toLowerCase()
        .replaceAll('-', '')
        .replaceAll(' ', '_')
        .replaceAll('\'', '');
    return 'recipe_$key';
  }

  /// Gets a translated recipe name based on the English name
  static String translateRecipeName(String englishName, String languageCode) {
    final key = _recipeNameToKey(englishName);
    return translate(key, languageCode) == key ? englishName : translate(key, languageCode);
  }

  /// Converts a goal type to its translation key
  static String _goalTypeToKey(String englishType) {
    String key = englishType.toLowerCase()
        .replaceAll('-', '')
        .replaceAll(' ', '_')
        .replaceAll('\'', '');
    return 'goal_type_$key';
  }

  /// Gets a translated goal type based on the English type
  static String translateGoalType(String englishType, String languageCode) {
    final key = _goalTypeToKey(englishType);
    return translate(key, languageCode) == key ? englishType : translate(key, languageCode);
  }
}
